ft_right_foot_calibration_matrix:
  [0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0 ]

ft_right_foot_unload: [1.65, 1.65, 1.65, 1.65, 1.65, 1.65]


ft_left_foot_calibration_matrix:
  [0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0]

ft_left_foot_unload: [1.65, 1.65, 1.65, 1.65, 1.65, 1.65]
